---
title: "Crochet"
author: "Sung Inkyung"
date: '2020 11 17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[generative art by Antonio Sanchez Chinchon] (https://github.com/aschinchon/crochet-patterns/blob/master/crochet.R)
```{r}
library(tidyverse)


pattern <- function(a, b, c = pi/2, d = pi/5, e = 4) {
  data_frame(
    x = accumulate(1:40, ~.x-sin((.y %% e)*c-ceiling((.y-1)/e)*d), .init = a),
    y = accumulate(1:40, ~.x+cos((.y %% e)*c-ceiling((.y-1)/e)*d), .init = b))
}


t <- seq(0, 2*pi, length.out = 120)
centers <- data_frame(x = sin(t), y = cos(t))


c  <- sample(seq(from = 0, to = 2*pi, by = pi/15), 1)
d  <- sample(seq(from = 0, to = 2*pi, by = pi/15), 1)
e  <- sample(1:20, 1)
  

apply(centers, 1, function(r) pattern(a = r[1], 
                                      b = r[2],
                                      c = c,
                                      d = d,
                                      e = e)) %>% 
  bind_rows(.id="df") %>% 
  ggplot() +
  geom_path(aes(x, y, group = df),
            color = "#9aa7c1", 
            alpha = 0.25) + 
  coord_fixed()+
  theme_void()
```

