---
title: "Folds"
author: "Sung Inkyung"
date: '2020 11 5'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[generative art by Antonio Sanchez Chinchon] (https://twitter.com/aschinchon)
```{r}
library(tidyverse)
tibble(t = (1:2739)*4.0786, 
       x = sin(t), 
       y = cos(t)) %>% 
ggplot(aes(x*t, y*t)) +
  geom_point(size=19, alpha=.1, shape=1)+ 
  coord_equal() +
  theme_void()
```

```{r}
tibble(t = (1:2300)*2.4432, 
       x = sin(t), 
       y = cos(t)) %>% 
ggplot(aes(x*t, y*t)) +
  geom_point(size=58, alpha=.1, shape=13)+ 
  coord_equal() +
  theme_void()
```
```{r}
n <- 500
tibble(r=sqrt(1:n),
       t=(1:n)*pi*(3-sqrt(5))) %>% 
  ggplot(aes(x=r*cos(t), y=r*sin(t)))+
  geom_point(aes(size=(n-r), color = r),
             shape=16) + 
  coord_equal() +
  cowplot::theme_nothing()
```

```{r}
seq(from=-10, to=10, by = 0.025) %>%
  expand.grid(x=., y=.) %>%
  ggplot(aes(x=(x+pi*sin(y)), 
             y=(y+pi*sin(x)))) +
  geom_point(alpha=.08, shape=20, size=0) + 
  theme_void()
```

```{r}
seq(-4,4,by=.012) %>%
  expand.grid(x=., y=.) %>%
  ggplot(aes(x=(1-abs(x)-sin(y^2)), y=(1+y-cos(x^2)))) +
  geom_point(alpha=.03, shape=20, size=0)+
  theme_void()+
  coord_polar()
```

```{r}
seq(from=-10, to=10, by = 0.05) %>%
  expand.grid(x=., y=.) %>%
  ggplot(aes(x=(x^2+pi*cos(y)^2), y=(y+pi*sin(x)))) +
  geom_point(alpha=.1, shape=20, size=0)+
  theme_void()+
  coord_equal()
```

