---
title: "TruchetCurve"
author: "Sung Inkyung"
date: '2020 12 19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyr)
library(dplyr)
library(ggforce)
```


```{r}
curves <- tribble(
  ~n, ~name, ~x, ~y,
  1, "lu", c(0, 0.5, 0.5), c(0.5, 0.5, 1),
  2, "rd", c(0.5, 0.5, 1), c(0, 0.5, 0.5),
  3, "ld", c(0, 0.5, 0.5), c(0.5, 0.5, 0),
  4, "ru", c(0.5, 0.5, 1), c(1, 0.5, 0.5)
  )

t = 900

tiles <- data.frame(col = rep(1:sqrt(t), sqrt(t)),
                    row = rep(1:sqrt(t), 
                              each = sqrt(t)),
                    n = sample(c(1, 2, 3, 4), 
                               replace = TRUE, 
                               size = t)) %>% 
  left_join(curves) %>% 
  unnest(c(x, y))

ggplot(tiles) +
  geom_bspline(aes(col + x, row + y,
                   group = interaction(col, row)), 
               size = 2, 
               n = 15, 
               color = "#838891", 
               lineend = "round") +
  coord_fixed() +
  theme_void() +
  theme(
    plot.background = element_rect(fill = "#62bfbf",
                                   color = NA)
  ) 

  ggsave(here::here("2020",  "TruchetCurve.png"), dpi = 320, height = 8, width = 8)
```
