---
title: "TruchetCornerTriangles"
author: "Sung Inkyung"
date: '2020 12 19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[aRt by Georgios Karamanis] (https://github.com/gkaramanis/aRt/blob/master/truchet/truchet-corner-triangles.R)
```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
```


```{r}
curves <- tribble(
  ~n, ~name, ~x, ~y,
  1, "lu", c(0, 0.5, 0), c(1, 1, 0.5),
  1, "rd", c(0.5, 1, 1), c(0, 0.5, 0),
  2, "ld", c(0, 0.5, 0), c(0, 0, 0.5),
  2, "ru", c(0.5, 1, 1), c(1, 1, 0.5)
)

t = 625

tiles <- data.frame(
  col = rep(1:sqrt(t), sqrt(t)),
  row = rep(1:sqrt(t), each = sqrt(t)),
  n = sample(c(1, 2), replace = TRUE, size = t)
) %>% 
  left_join(curves) %>% 
  unnest(c(x, y))


ggplot(tiles) +
  geom_polygon(aes(col + x, row + y, group = interaction(row, col, name)), 
               size = 0.25, 
               color = "#101820ff", 
               fill = "#ffc3a0") +
  coord_fixed() +
  theme_void() +
  theme(
    plot.background = element_rect(fill = "#f2aa4cff", 
                                   color = NA)
  ) 

  ggsave(here::here("2020", "TruchetCornerTriangles.png"), dpi = 320, height = 8, width = 8)
```

