---
title: "2.Dithering"
author: "Sung Inkyung"
date: '2022 1 2'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[dithr package by @coolbutuseless](https://coolbutuseless.github.io/2018/02/05/dithr-package-for-error-diffusion-dithering-in-r/)
```{r}
library(dithr)
library(EBImage)
library(magick)
library(dplyr)
```

```{r}
im <- magick::image_read('trees.png') %>%
  magick::image_convert(type='grayscale') %>%
  magick::image_scale(geometry="75%")

m <- magick::as_EBImage(im)@.Data

dithr::plot_matrix(m)

dithered_matrix <- dither(m, edm = diffusion_matrix$floyd_steinberg, threshold = 0.6) #atkinson


plot_matrix(dithered_matrix)
```


```{r}
image_yarn <- magick::image_read('C:/Users/inkyscope/Documents/projectR/30DayChartChallenge/data/yarn.png') %>%
  magick::image_convert(type='grayscale') %>%
  magick::image_scale(geometry="75%")

yarn <- magick::as_EBImage(image_yarn)@.Data

dithr::plot_matrix(yarn)

dithered_yarn <- dither(yarn, edm = diffusion_matrix$atkinson, threshold = 0.6) 
plot_matrix(dithered_yarn)

```