---
title: "PoissonedPoints"
author: "Sung Inkyung"
date: '2021 1 28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[poissoned by coolbutuse](https://coolbutuseless.github.io/2019/06/25/poissoned-a-package-for-poisson-disc-sampling/)
```{r}
library(tidyverse)
library(poissoned)
```


```{r}
set.seed(123)
points <- poisson_disc(ncols = 100, 
                       nrows = 100, 
                       cell_size = 5, 
                       verbose = TRUE)

ggplot(points) +
  geom_point(aes(x, y, size = y ^ 2, color = x/y)) + #size = y %/% 20
  geom_point(aes(y, x, size = y ^ 2)) +
  scale_size_continuous(range = c(0.7, 1.8)) +
  scale_y_reverse() +
  scale_color_distiller(palette = "PRGn") +
  coord_fixed() +
  theme_void() +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.title = element_blank()
  ) 

ggsave(here::here("2021", "Points", "PoissonedPoints.png"), dpi =320, width = 20, height = 20, units = "cm")
```

```{r}
points <- poissoned::poisson_disc(ncols = 30, 
                                  nrows = 20, 
                                  cell_size = 10, 
                                  keep_boundary = TRUE, 
                                  verbose = TRUE)

poisson_disc = 300*200
minimum_distance = 14.14

points$boundary <- with(points, x < 0 | y < 0 | x > 300 | y > 200)

ggplot(points) +
  geom_rect(xmin = 0, 
            xmax = 300, 
            ymin = 0, 
            ymax = 200, 
            fill = NA, 
            colour = '#a0a0a0', 
            linetype = 2) + 
  geom_point(aes(x, y, colour = boundary)) +
  theme_void() +
  coord_fixed() +
  theme(legend.position = 'none')
```

### Source [genuary2021 by gkaramanis] (https://github.com/gkaramanis/aRtist/blob/main/genuary/2021/2021-27/2021-27.R)
```{r}
df <- data.frame(
  x = 1:100,
  y = 1:100) %>% 
  expand(x, y) 

ggplot(df) +
  geom_point(aes(x, y, size = y ^ 2)) +
  geom_point(aes(y, x, size = y ^ 2)) +
  scale_size_continuous(range = c(0.7, 1.8)) +
  scale_y_reverse() +
  coord_fixed() +
  theme_void() +
  theme(
    legend.position = "none"
  )
```

