---
title: "3. Space"
author: "Sung Inkyung"
date: '2022 1 5'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Source[genuary2022 by @geokaramanis](https://github.com/gkaramanis/aRtist/blob/main/genuary/2022/2022-03/2022-03.R)
```{r}
#devtools::install_github("BlakeRMills/MetBrewer") 
library(ggshadow)
library(ggplot2)
library(MetBrewer)

pals <- MetBrewer::met.brewer("Monet")

set.seed(2022)

n = 80

snows <- data.frame(
  x = runif(n * 2),
  y = runif(n * 2),
  size = runif(n * 2, 0, 0.2),
  x2 = runif(n),
  y2 = runif(n),
  size2 = runif(n, 0, 2), #n, 0, 3
  color2 = pals[runif(n, 3, 7)] #n, 5, 10
)

ggplot(snows) +
  geom_point(aes(x, y, size = size, color = "gray65")) +
  geom_glowpoint(aes(x2, y2, size = size2, color = color2, shadowsize = size2  ^ 1.2)) +
  scale_size_continuous(range = c(0.1, 3)) + #c(0.1, 4)
  scale_color_identity() +
  coord_fixed(clip = "off") +
  theme_void() +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "gray10",
                                   color = NA)
  )

ggsave("Space.png", dpi = 320)
```

