---
title: "Polar2"
author: "Sung Inkyung"
date: '2021 1 12 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###Source[Radial Patterns in ggplot2 by ijeamaka-anyene] (https://github.com/Ijeamakaanyene/patterns)
```{r}
library(ggplot2)
library(dplyr)
```


```{r}
n_lines <- 10

circle <-  tibble(
  x = rep(0, 10,
          length.out = n_lines),
  xend = seq(from = 5, 
             to = 10,
             length.out = n_lines),
  y = 1:n_lines,
  yend = 1:n_lines
)

 ggplot(data = circle) +
  geom_segment(aes(x = x, y = y,
                   xend = xend, yend = yend),
               size = .9,
               color = "#ffc107") +
  scale_x_continuous(limits = c(0, 15)) +
  scale_y_continuous(limits = c(-5, n_lines)) +
  labs(caption = "Graphic: Sung Inkyung") +
  coord_polar() +
  theme(
    plot.background = element_rect(fill = "#4d164d"),
    panel.background = element_rect(fill = "#4d164d"),
    plot.caption = element_text(size = 6,
                                color = "#e2cbba"),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )
 
 ggsave(here::here("figures", "polar2.png"), width = 10, height = 10, units = "cm")

```


```{r}
```

