---
title: "Polar1"
author: "Sung Inkyung"
date: '2021 1 12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(gganimate)
```
###Source[Radial Patterns in ggplot2 by ijeamaka-anyene] (https://github.com/Ijeamakaanyene/patterns)

```{r}

lines <-  tibble(
  x = seq(0, 19, by = .5),
  xend = x, 
  y = c(rep(c(5, 10), 19), 5),
  yend = rep(0, 39),
  speed = 3
)

dots <-  lines %>% 
  select(x, y)

# Static Plot
plot1 <- ggplot() +
  geom_segment(data = lines,
               aes(x = x, 
                   xend = xend,
                   y = y,
                   yend = yend),
               color = "#ff3961") +
  geom_point(data = dots,
             aes(x, y),
             color = "#ff3961") +
  labs(caption = "Graphic: Sung Inkyung") +
  scale_x_continuous(limits = c(0, 19)) +
  scale_y_continuous(limits = c(-5, 10)) +
  coord_polar() +
  theme(plot.background = element_rect(fill = "#359c9a"),
        panel.background = element_rect(fill = "#359c9a"),
        panel.grid = element_blank(),
        plot.caption = element_text(size = 6,
                                    color = "#e2cbba"),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank())

ggsave(here::here("figures", "polar1.png"), width = 10, height = 10, units = "cm")
 
```

