---
title: "polar3"
author: "Sung Inkyung"
date: '2021 1 12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###Source[Radial Patterns in ggplot2 by ijeamaka-anyene] (https://github.com/Ijeamakaanyene/patterns)
```{r}
library(ggplot2)
library(dplyr)
```


```{r}
inner_circle <-  tibble(
  x = seq(0, 19, .5),
  xend = x, 
  y = rep(0, 39),
  yend = rep(3, 39)
)

outer_circle <-  center_circle %>% 
  mutate(y = yend, 
         yend = yend + 6)

ggplot() +
  geom_segment(data = center_circle,
               aes(x = x, xend = xend,
                   y = y, yend  = yend),
               size = .5, 
               color = "gray20") +
  geom_segment(data = outer_circle,
               aes(x = x, xend = xend,
                   y = y, yend = yend),
               size = 2, 
               color = "gray20") +
  scale_y_continuous(limits = c(-2, 10)) +
  labs(x = "",
       y = "",
       caption = "Graphic: Sung Inkyung") + 
  theme_light() +
  theme(
    plot.caption = element_text(size = 6,
                                color = "white"),
    panel.grid = element_blank()
  )
  
```


```{r}
ggplot() +
  geom_segment(data = center_circle,
               aes(x = x, xend = xend,
                   y = y, yend  = yend),
               size = .5, 
               color = "#800080") +
  geom_segment(data = outer_circle,
               aes(x = x, xend = xend,
                   y = y, yend = yend),
               size = 2.5, 
               color = "#4d164d") +
  scale_y_continuous(limits = c(-2, 10)) +
  labs(caption = "Graphic: Sung Inkyung") + 
  coord_polar() +
  theme(
    plot.background = element_rect(fill = "#ccd9ea"),
    panel.background = element_rect(fill = "#ccd9ea"),
    plot.caption = element_text(size = 6,
                                color = "#359c9a",
                                margin = margin(b = 3, r = 20)),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

ggsave(here::here("figures", "ploar3.png"), width = 10, height = 10, units = "cm")
```

