---
title: "500Lines"
author: "Sung Inkyung"
date: '2021 1 25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[genuay2021 by gkaramanis] (https://github.com/gkaramanis/aRtist/blob/main/genuary/2021/2021-24/2021-24.R)
```{r}
library(tidyverse)
library(ggbump)
library(wesanderson)

names(wes_palettes)
```


```{r}
s = 1
e = 5
f = 0.5

lns <- data.frame(
  a <- seq(0, 2*pi, length.out = 500)
) %>% 
  mutate(
    x = s * cos(a + f),
    y = s * sin(a + f),
    xend = e * cos(a),
    yend = e * sin(a)
  )

pal <- wes_palette("Royal2", 500, type = "continuous")

ggplot(lns) +
  geom_sigmoid(aes(x = x, y = y,
                   xend = xend, yend = yend, 
                   group = a, 
                   color = factor(y ^ 2)), 
               size = 0.5, smooth = 6) +
  scale_color_manual(values = pal) +
  coord_fixed() +
  theme_void() +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "#4f4a4b", 
                                   color = NA)
  ) 

  ggsave(here::here("2021", "Lines", "500Lines.png"), dpi = 320, width = 13, height = 13, units = "cm")
```

