---
title: "Perlin_Spiral"
author: "Sung Inkyung"
date: '2021 12 16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[ambient package by Thomas ] (https://www.data-imaginist.com/2020/a-noisy-start/)
```{r}
library(ambient)
library(dplyr)
library(ggplot2)
```


```{r}
# frequency determines the granualarity of the features in the noise


spiral <- data.frame(a = seq(200, 1000, by = 0.01)) %>% 
  mutate(
    x_off = a * cos(a),
    y_off = a* sin(a),
    r = normalise(gen_perlin(x_off, y_off,
                             frequency = 0.03),
                  from = c(-1, 1),
                  to = c(100, 120)),
    x = a * r * cos(a),
    y = a * r * sin(a)
  )

ggplot(spiral, aes(x, y))+
  geom_path(color = "gray10", size = 0.3) +
  coord_fixed() +
  theme_void() +
  theme(plot.background = element_rect(fill = "gray95",
                                       color = NA))

ggsave(here::here("2021", "Lines", "Perlin_Spiral.png"), dpi = 320)
```

