---
title: "t-SNE"
author: "Sung Inkyung"
date: '2021 11 8'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[art by Claus O. Wilke] (https://clauswilke.com/art/post/tsne-generative)
```{r}
library(tidyverse)
library(Rtsne)
library(paletteer)
library(patchwork)
```


```{r}
setup_coords <- function(groups = 3, n = 100, sd = .05) {
  tibble(
    x = rep(1:groups, each = n) + rnorm(groups*n, sd = sd),
    y = rep(seq(from = 0, to = 10, length.out = n), groups) + 
          rnorm(groups*n, sd = sd),
    group = rep(letters[1:groups], each = n)
  )
}

setup_coords() %>%
  ggplot(aes(x, y, color = group)) + 
  geom_point() +
  scale_color_paletteer_d("rockthemes::nodoubt", guide = "none")
```
### Source[scale function] (https://www.rdocumentation.org/packages/viridis/versions/0.6.1/topics/scale_fill_viridis) 

option
A character string indicating the color map option to use. Eight options are available:

"magma" (or "A"), "inferno" (or "B"), "plasma" (or "C"), "viridis" (or "D"), "cividis" (or "E"), "rocket" (or "F"), "mako" (or "G"), "turbo" (or "H")

```{r}
do_tsne <- function(coords, perplexity = 5){
  tsne_fit <- coords %>% 
    select(x, y) %>% 
    scale() %>% 
    Rtsne(perplexity = perplexity, 
          mix_iter = 500,
          check_duplicates = FALSE)
  
  tsne_fit$Y %>% 
    as.data.frame() %>% 
    cbind(select(coords, -x, -y))
}

setup_coords() %>%
  do_tsne() %>%
  ggplot(aes(V1, V2, color = group)) + 
  geom_point() +
  scale_color_paletteer_d("rockthemes::nodoubt", guide = "none") +
  coord_fixed() + 
  theme_void()

```


```{r}
make_tsne_plot <- function(groups = 5, n = 200, sd = 0, perplexity = 5) {
  setup_coords(groups = groups, n = n, sd = sd) %>% 
    do_tsne(perplexity) %>% 
    ggplot(aes(V1, V2, color = group)) +
    geom_point() +
    scale_color_paletteer_d("rockthemes::nodoubt", guide = "none") +
    coord_fixed() +
    theme_void() +
    theme(plot.margin = margin(20, 20, 20, 20),
          panel.border = element_rect(color = "black",
                                      fill = NA))
}

make_tsne_plot(groups = 5, sd = 0)
```
  
```{r}
patchtsne <- make_tsne_plot(groups = 5, sd = 0, perplexity = 2) |
  make_tsne_plot(groups = 5, sd = 0, perplexity = 7) |
  make_tsne_plot(groups = 5, sd = 0, perplexity = 15)

patchtsne + plot_annotation(
  title = "2021 t-Sne_Series",
  caption = "Credit: Claus O. Wilke | Graphic: Sung Inyung"
)  &
  theme(plot.title = element_text(size = 20),
        plot.caption = element_text(size = 7,
                                    margin = margin(b = 20)))

ggsave(here::here("2021", "Lines", "tSne_Series.png"), width = 20, height = 12, units = "cm")

```


```{r}
make_tsne_plot(groups = 5, sd = 0)|
  make_tsne_plot(groups = 5, sd = 0.05) |
  make_tsne_plot(groups = 5, sd = 0.2)
```

```{r}
make_tsne_plot(groups = 5, sd = 0, perplexity = 7)|
  make_tsne_plot(groups = 5, sd = 0.05, perplexity = 7) |
  make_tsne_plot(groups = 5, sd = 0.2, perplexity = 7)
```
