---
title: "0123"
author: "Sung Inkyung"
date: '2021 1 23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[genuary2021 by gkaramanis] (github.com/gkaramanis/aRtist/blob/main/genuary/2021/2021-18/2021-18.R)
```{r}
library(tidyverse)
library(paletteer)
```


```{r}
n = 45

df <- data.frame(y = 1:n) %>% 
  rowwise() %>% 
  mutate(x = list(rnorm(n, mean = n/20, sd = n/5))) %>% 
  unnest(x)

ggplot(df) +
  geom_tile(aes(x*4, y - x,
                group = y, 
                height = x, 
                width = x,
                fill = factor(y %/% 3)),
            color = NA, 
            alpha = .1) +
  scale_fill_paletteer_d("Redmonder::qPBI") +
  xlim(-100, 100) +
  ylim(-20, 70) +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#171716",
                                       color = NA)) +
  ggsave(here::here("figures", "0123.png"), dpi = 320, width = 10, height = 7, units = "cm")


```
```{r}

n= 50

df <- data.frame(y = 1:n) %>% 
  rowwise() %>% 
  mutate(x = list(rnorm(n, mean = n/20, sd = n/5))) %>% 
  unnest(x)


ggplot(df) +
  geom_tile(aes(x*4, y - x * c(1, -1),
                group = y, 
                height = x, 
                width = x,
                fill = factor(y %/% 3)),
            color = NA, 
            alpha = .1) +
  scale_fill_paletteer_d("palettetown::cascoon") +
  xlim(-100, 100) +
  ylim(-20, 70) +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "gray15",
                                       color = NA))
```


```{r}

n= 55

df <- data.frame(y = 1:n) %>% 
  rowwise() %>% 
  mutate(x = list(rnorm(n, mean = n/20, sd = n/5))) %>% 
  unnest(x)


ggplot(df) +
  geom_tile(aes(x*4, y - x * c(1, -1),
                group = y, 
                height = x, 
                width = x,
                fill = factor(y %/% 3)),
            color = NA, 
            alpha = .1) +
  scale_fill_paletteer_d("Redmonder::qMSOBu2") +
  xlim(-100, 100) +
  ylim(-20, 70) +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "#1b1c1c",
                                       color = NA))
```
