---
title: "tridoku"
author: "Sung Inkyung"
date: '2019 9 24 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### source[coloring sudokus by Antonio Sánchez Chinchón](https://fronkonstin.com/2018/06/01/coloring-sudokus/)
(https://github.com/aschinchon/sudokus-colored/blob/master/sudokus_colored.R)

```{r}
library(gtools)
library(dplyr)
library(sudoku)
library(ggplot2)
library(here)
```

```{r}
# permuations of three elements (6 in toal) to create all possible permuations of subsequent sudokus
# column k to do cross joins later
permutations(n = 3, r = 3, v = 1:3) %>% 
  as.data.frame() %>% 
  mutate(k = 1) <- perm

```

```{r}
# cross join permuations 4 times
# use last three colums to interchange groups of columns 
# first nine to interchange within columns
perm %>% 
  inner_join(perm, by = "k") %>% 
  inner_join(perm, by = "k") %>% 
  inner_join(perm, by = "k") %>% 
  select(-k) <- total_all
```

```{r}
# rename columns to make it understable
colnames(total_all) = c(paste0("v", 1:9), "c1", "c2", "c3")
```

```{r}
# generate all possibilities. Each row of total_all is a possible
# reordering of columns to create a new sudoku
total_all %>% 
  mutate_at(vars(v1:v3), function(.) .+3*total_all[,"c1"]-3) %>% 
  mutate_at(vars(v4:v6), function(.) .+3*total_all[,"c2"]-3) %>% 
  mutate_at(vars(v7:v9), function(.) .+3*total_all[,"c3"]-3) %>% 
  select(v1:v9)-> total_all
```

```{r}
n = 3 # n can take value from 1 to 9
data <- data.frame()
total = total_all
```
```{r}
# This loop generates n disjoint sudokus from a base on (when i is equal to 1)
# and resampling from total_all
for (i in n:1)
{
  if(i==n)
  {
    sudoku <- generateSudoku(0)
    data.frame(level=sudoku %>% as.vector(), size=i)->new
    compare=apply(total, 1, function(x) sum(abs(x-(1:9))==0))
  } else
  {
    total %>% sample_n(1) -> tran
    sudoku_trans <- sudoku[tran %>% as.numeric,]
    data.frame(level=sudoku_trans %>% as.vector(), size=i)->new
    compare=apply(total, 1, function(x) sum(abs(x-as.numeric(tran))==0))
  }
  expand.grid(x=1:9, y=1:9) %>% cbind(new) %>% rbind(data) -> data
  total=total[which(compare==0),] #  To guaranteeing subsequent sudokus are disjoint from previous
  
}

```

```{r}
greenfocus = c("#41AB5D", "#252525", "#525252", "#737373", "#969696", "#BDBDBD", "#D9D9D9", "#F0F0F0")

plot <- ggplot(data, aes(group = size, fill = level)) +
  geom_rect(aes(xmin = x - ((n - (size - 1)) / n)*0.5,
                xmax = x + ((n - (size - 1)) / n)*0.5,
                ymin = y - ((n - (size - 1)) / n)*0.5,
                ymax = y + ((n - (size - 1)) / n)*0.5)) +
  scale_fill_gradientn(colors = greenfocus) +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "none")

plot

ggsave(here ("figures", "EnjoinGreenfocus.png"), height = 4, width =4, units = "in", dpi = 600)
```


```{r plot}
 tol9qualitative=c("#332288", "#88CCEE", "#44AA99", "#117733", "#999933", "#DDCC77", "#CC6677", "#882255", "#AA4499")

plot <- ggplot(data, aes(group = size, fill = level)) +
  geom_rect(aes(xmin = x - ((n - (size - 1)) / n)*0.5,
                xmax = x + ((n - (size - 1)) / n)*0.5,
                ymin = y - ((n - (size - 1)) / n)*0.5,
                ymax = y + ((n - (size - 1)) / n)*0.5)) +
  scale_fill_gradientn(colors = tol9qualitative) +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "none")

plot

ggsave(here ("figures", "EnjoinTol9.png"), height = 4, width =4, units = "in", dpi = 600)

```


```{r}
dark6equal = c("#1B9E77", "#66A61E", "#7570B3", "#D95F02", "#E6AB02", "#E7298A")

plot <- ggplot(data, aes(group = size, fill = level)) +
  geom_rect(aes(xmin = x - ((n - (size - 1)) / n)*0.5,
                xmax = x + ((n - (size - 1)) / n)*0.5,
                ymin = y - ((n - (size - 1)) / n)*0.5,
                ymax = y + ((n - (size - 1)) / n)*0.5)) +
  scale_fill_gradientn(colors = dark6equal) +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "none")

plot
```

