---
title: "Curves and Straights"
author: "Sung Inkyung"
date: '2021 10 28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source [RecreationThursday by MayaGans] (https://github.com/MayaGans/recreating_art/blob/main/code/curves_and_straights.R)
### Source [Curves and Straight Series 1948 by Alfred Hlito] (https://www.moma.org/collection/works/205953)

```{r}
library(ggplot2)
```


```{r}
green <- "#37b73a"
red <- "#e90d19"
blue <- "#5099e6"
black <- "#282828"
yellow <- "#c5b856"

curves_straight <- data.frame(
  x1 = c(c(3, 3, 3, 3, 3), c(13, 13, 13, 13)),
  y1 = c(c(-2, -6, -7.5, -9, -25), c(-2, 2, 3.5, 5)),
  xend = c(c(5, 5, 5, 5, 5), c(15, 15, 15, 15)),
  yend = c(c(-2, -6, -7.5, -9, -25), c(-2, 2, 3.5, 5)),
  color = c(green, red, blue, black, red, red, green, blue, black)
)

plot <- ggplot() +
  geom_segment(data = curves_straight,
               aes(x = x1, y = y1,
                   xend = xend, yend = yend),
               color = curves_straight$color,
               size = 1.6) +
  geom_curve(aes(x = 5, y = -20,
                 xend = 9, yend = 30),
             size = 1.6, color = yellow, 
             curvature = 0.4) +
  geom_curve(aes(x = 9.4, y = -7, 
                 xend = 9.4, yend = -30),
             size = 1.6, color = blue,
             curvature = 0.4) +
  geom_segment(aes(x = 8, y = -2, 
                   xend = 13, yend = -20),
               size = 1.6) +
  guides(color = F) +
  theme_void() +
  theme(plot.background = element_rect(fill = "#e5decd",
                                       color = NA),
        plot.margin = margin(-1, 5, 4, 5, unit = "cm"))

ggsave(here::here("figures", "Curves_Straights.png"), dpi = 320, width = 10, height = 10)

```
