---
title: "MoMA Collection"
author: "Sung Inkyung"
date: '2021 10 30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[30DayChartChallenge by Kelly Cotton] (https://github.com/kellycotton/30DayCharts/blob/main/code/Day10/Day10.R)
### Source[Data from MoMA] (https://github.com/MuseumofModernArt/collection)
```{r}
library(tidyverse)
library(ggtext)
```

```{r}
moma_artworks <- read_csv('https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artworks.csv')

moma_artworks %>% 
  count(Classification, sort = T)
```


```{r}
df <- moma_artworks %>% 
  filter(Classification != "(not assigned") %>% 
  mutate(Classification = case_when(
    str_detect(Classification, "Archive") ~ "Archives",
    TRUE ~ Classification)) %>% 
  mutate(Classification = fct_lump(Classification, n = 10, other_level =  "Other")) %>% 
  group_by(Classification) %>% 
  summarise(total = n()) %>% 
  mutate(ymax = cumsum(total),
         ymin = lag(ymax, n = 1, default = 0))

```

```{r}
pals <- c("#f51b00", "#ff8400", "#f3d265", "#82ac85", "#5a8ac4", "#01344b", "#987d84", "#b08b3f", "#231f20", "#393b45", "#8f8275")

plot <- df %>% 
  ggplot() +
  geom_rect(aes(xmin = 0, xmax = 11,
                ymin = ymin, ymax = ymax, 
                fill = Classification)) +
  scale_fill_manual(values = pals,
                    name = NULL) +
  coord_polar() +
  guides(fill = guide_legend(nrow = 1, 
                             label.position = "bottom")) +
  labs(title = "The MoMA Collection",
       subtitle = "What is most common type of art at the Muesum of Modern Art?<br>**33,025 photographs.** The design below is modeled after the<br> abstract artist Hilma af Klimt's *Series VII. Picture of the Starting<br>Point*, 1920.", 
       caption = "Source: the Museum of Modern Art | Credit: @kllycttn | Graphic: Sung Inkyung") +
  theme_void() +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 6, 
                                   face = "bold"),
        legend.box.margin = margin(0, 0, 15, 0),
        plot.background = element_rect(fill = "#d6cec3",
                                       color = "#d6cec3"),
        panel.background = element_rect(fill = "#d6cec3",
                                       color = "#d6cec3"),
        plot.title = element_text(size = 30, 
                                  hjust = 0.5),
        plot.subtitle = element_markdown(size = 13,
                                         hjust = 0.5),
        plot.caption = element_text(size = 7,
                                    margin = margin(b = 5, r = 7)))


ggsave(here::here("figures", "MoMA_Collection.png"), dpi = 320, width = 17, height = 20, units = "cm")
```

