---
title: "Mountain"
author: "Sung Inkyung"
date: '2020 3 7 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(here)


set.seed(2020)

ngroup=30
names <- paste("G_",seq(1,ngroup),sep="")
DAT <- data.frame()

for(i in seq(1:30)){
    data=data.frame( matrix(0, ngroup , 3))
    data[,1]=i
    data[,2]=sample(names, nrow(data))
    data[,3]=prop.table(sample( c(rep(0,100),c(1:ngroup)) ,nrow(data)))
    DAT <-  rbind(DAT,data)
    }
colnames(DAT) <- c("Year","Group","Value")
DAT <- DAT[order( DAT$Year, DAT$Group) , ]


pal <-  brewer.pal(11, "BrBG") 
pal <-  colorRampPalette(pal)(ngroup)
pal <-  pal[sample(c(1:length(pal)) , size=length(pal) ) ]

art <- DAT %>% 
  ggplot(aes(x=Year, y=Value, fill=Group )) + 
    geom_area(alpha=1  )+
    theme_bw() +
    #scale_fill_brewer(colour="red", breaks=rev(levels(DAT$Group)))+
    scale_fill_manual(values = pal)+
     theme(
        text = element_blank(),
        line = element_blank(),
        title = element_blank(),
        legend.position="none",
        panel.border = element_blank(),
        panel.background = element_blank())

ggsave(here("figures", "Mountain.png"), width = 10, height = 8, units = "cm")
```

