---
title: "Untitled"
author: "Sung Inkyung"
date: '2021 1 23 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Source[Poissoned Package by @coolbutuseless] (https://coolbutuseless.github.io/2019/06/25/poissoned-a-package-for-poisson-disc-sampling/)

### Coding Cred[aRtist by gkaramanis] (https://github.com/gkaramanis/aRtist/blob/main/genuary/2021/2021-22/2021-22.R)
```{r}
library(tidyverse)
library(poissoned)

devtools::install_github("coolbutuseless/poissoned") 
```


```{r}
points <- poisson_disc(400, 400, 0.05)

ly = 10

df_points <- points %>% 
  filter(!between(y, 0.995 * ly, 1.005 * ly))

ggplot(df_points) +
  geom_point(aes(x, y, size = (x + y) %% 3,
                 color = (y - x) %% 3)) +
  scale_size_continuous(range = c(0.05, 0.3)) +
  scale_color_gradient(high = "#141433", low = "#5b797e") +
  coord_fixed(expand = F) +
  theme_void() +
  theme(legend.position = "none",
        plot.background = element_rect(fill = "gray90",
                                       color = NA)) +
  ggsave(here::here("figures", "poissoned.png"), dpi = 320, width = 7, height = 7)
```

