---
title: "polar8"
author: "Sung Inkyung"
date: '2021 1 12 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Source[Radial Patterns in ggplot2 by ijeamaka-anyene] (https://github.com/Ijeamakaanyene/patterns)
```{r}
library(ggplot2)
library(dplyr)
```


```{r}
n_lines <-  20

thin_lines <- tibble(
  y = 1:n_lines,
  yend = 1:n_lines,
  x = 0,
  xend = n_lines
)

set.seed(100)
thick_lines <- tibble(
  y = c(1:n_lines, 1:n_lines),
  yend = c(1:n_lines, 1:n_lines),
  x = runif(n_lines*2, min = 0, max = 15),
  xend = x + runif(n_lines*2, min = 1, max = 5)
)
```


```{r}
ggplot() +
  geom_segment(data = thin_lines,
               aes(x = x, y = y,
                   xend = xend, yend = yend),
               color = "#c5a4e7",
               size = .5) +
  geom_segment(data = thick_lines,
               aes(x = x, xend = xend, 
                   y = y, yend= yend),
               color  = "#4b0082",
                   szie = 1.5, 
                   lineend = "round") +
  scale_x_continuous(limits = c(0, 20)) +
  labs(caption = "Graphic: Sung Inkyung") +
  coord_polar() +
  theme(
    plot.background = element_rect(fill = "#359c9a"),
    panel.background = element_rect(fill = "#359c9a"),
    plot.caption = element_text( size = 6,
                                color = "#20208b"),
    panel.grid = element_blank(),
    legend.position = "none",
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )

 ggsave(here::here("figures", "polar8.png"), width = 10, height = 10, units = "cm")                      
                 
```
### interesting
