---
title: "polar10"
author: "Sung Inkyung"
date: '2021 1 12 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
```
###Source[Radial Patterns in ggplot2 by ijeamaka-anyene] (https://github.com/Ijeamakaanyene/patterns)

```{r}
increment <- .05

circle1 <- tibble(
  x = seq(0, 5, by = increment),
  xend = seq(0, 5, by = increment),
  y = 0,
  yend = 1.5,
  type = LETTERS[1]
)

circle2 <- tibble(
  x = seq(0, 5, by = increment),
  xend = seq(0, 5, by = increment),
  y = 1.5,
  yend = 3,
  type = LETTERS[2]
)

circle3 <- tibble(
  x = seq(0, 5, by = increment),
  xend = seq(0, 5, by = increment),
  y = 3,
  yend = 4.5,
  type = LETTERS[3]
)

pals <- c("#359c9a", "#eac424", "#4b0082")

bind_rows(circle1, circle2, circle3) %>% 
  ggplot() +
  geom_segment(aes(x = x, xend = xend,
                   y = y, yend = yend,
                   color = type)) +
  scale_color_manual(values = pals)



```


```{r}
bind_rows(circle1, circle2, circle3) %>% 
  ggplot() +
  geom_segment(aes(x = x, xend = xend,
                   y = y, yend = yend,
                   color = type)) +
  scale_color_manual(values = pals) +
  coord_polar() +
   theme(
     legend.position = "none",
    plot.background = element_rect(fill = "#a18f24"),
    panel.background = element_rect(fill = "#a18f24"),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank())
```

