---
title: "polar21"
author: "Sung Inkyung"
date: '2021 1 12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###Source[Radial Patterns in ggplot2 by ijeamaka-anyene] (https://github.com/Ijeamakaanyene/patterns)
```{r}
library(ggplot2)
library(dplyr)
library(ggforce)
```


```{r}
circle <- tibble(
  len = seq(0, 2*pi, 
            length.out = 61),
  x = sin(len),
  y = cos(len),
  type = 1:61
)

left <-  circle %>% 
  filter(x < 0, 
         y > -1) %>% 
  mutate(xend = -0.02)

right <- circle %>% 
  filter(x > 0, y > -1) %>% 
  mutate(xend = 0.02)

ggplot() +
  geom_segment(data = left,
               aes(x = x, xend = xend, 
                   y = y, yend = y),
               lineend = "round",
               color = "white",
               size = 1.1) +
  geom_segment(data = right, 
               aes(x = x, xend = xend, 
                   y = y, yend = y),
               lineend = "round",
               color = "white",
               size = 1.1) +
  scale_x_continuous(limits = c(-1.5, 1.5)) +
  scale_y_continuous(limits = c(-1.5, 1.5)) +
  coord_fixed() +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "#4b0082"),
    panel.background = element_rect(fill = "#4b0082"),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )
```

