---
title: "polar4"
author: "Sung Inkyung"
date: '2021 1 12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(ggforce)
```

###Source[Radial Patterns in ggplot2 by ijeamaka-anyene] (https://github.com/Ijeamakaanyene/patterns)

```{r}
dots <- expand.grid(x = seq(1, 10, .2),
                    y = c(1:10))

dots <- dots %>% 
  mutate(type = sample(c("Y", "N"), 460,
                       replace = T)) %>% 
  filter(type == "Y")

outline <- tibble(
  x = c(.9, .9, .9, 10.1),
  xend = c(10.1, 10.1, .9, 10.1),
  y = c(.55, 11, .55, .55),
  yend = c(.55, 11, 11, 11)
)
```


```{r}
ggplot() +
  geom_point(data = dots,
             aes(x = x, y = y),
             color = "#3486b8",
             alpha = .2,
             size= 3) +
  geom_point(data = dots,
             aes(x = x, y = y),
             color = "#3486b8") +
  geom_segment(data = outline,
               aes(x = x, xend = xend,
                   y = y, yend = yend),
               color = "#3486b8") +
  geom_segment(data = outline,
               aes(x = x, xend = xend,
                   y = y, yend = yend),
               alpha = 0.2,
               size = 1.4,
               color = "#3486b8") +
  scale_y_continuous(limits = c(-2, 11)) +
  scale_x_continuous(limits = c(0.5, 10.5)) +
  coord_polar() +
  #labs(caption = "Graphic: Sung Inkyung") +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "#191919"),
    panel.background = element_rect(fill = "#191919"),
    plot.caption = element_text(size = 6,
                                color = "#e2cbba"),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  )
  
```
### hard to follow

