---
title: "Swirl"
author: "Sung Inkyung"
date: '2021 12 18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(metR)
library(ambient)
library(wesanderson)
```
### Source[generative art by @geokaramanis] (https://github.com/gkaramanis/aRtist/blob/main/swirl/swirl.R)

```{r}
r_df <- expand.grid(x = 1:300, y = 1:300)
r_df$dx <- gen_perlin(r_df$x, r_df$y, frequency = 0.15)
r_df$dy <- gen_perlin(r_df$x, r_df$y, frequency = 0.25)


ggplot(r_df,
       aes(x = x, y = y)) +
  geom_streamline(aes(dx = dx, 
                      dy = dy, 
                      size = ..step..,
                      alpha = ..step..),
                  arrow = NULL,
                  lineend = "round",
                  L = 20, 
                  color = "gray20") +
  scale_size(range = c(0, 0.5),
             guide = "none") +
  scale_alpha(range = c(0, 0.8),
              guide = "none") +
  coord_fixed(expand = FALSE) +
  theme_void() +
  theme(plot.background = element_rect(fill = "gray96",
                                       color = NA),
        plot.margin = margin(5, 5, 5, 5))

ggsave(here::here("figures", "swirl.png"), dpi = 320, width = 6, height = 6)
```

